on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: PenguinCabinet/action-to-detect-404-URLs@main
        with:
          working_directory: "./" # The directory path to check
          filter_mode: "deny" # "allow" mode or "deny" mode
          filter_status_code: "4.." # Detects URLs with status codes in the 400 range. Can be written using regular expressions.
          detect_URLs_that_cannot_connect_to_the_server: true # Whether to detect when the server cannot be connected
          wait_time: 1 # Request sending interval(second)